name: CI for Java Invoice
on: [push]
jobs:
  test:
    strategy:
           matrix:
             node: [8,13,15]
    name: Unit tests on Java ${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:

          java-version: ${{ matrix.node }}
          distribution: 'adopt'
      - name: Test
        run: mvn test
      - name: CheckStyle
        run: mvn checkstyle:check